### ISSUE TITLE
Option for turning off Ceph monitoring

### ISSUE THREAD

**Issue by shane-c** [rcbops/rpc-openstack#492]
I might just be missing this variable somewhere, but on r11.0.1, setup-maas.yml tries to discover ceph facts even though I'm not using ceph in this deployment. I don't see any way to turn this off in user_extras_variables.yml or anywhere else. In a deployment that is not using ceph how is setup-maas.yml supposed to complete?

TASK: [rpc_maas | Discover Ceph facts] ****************************************
fatal: [compute01] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_scheduler_container-638e2856] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_horizon_container-f3df59bf] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_horizon_container-422f2991] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_utility_container-0276d803] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_keystone_container-2d73e396] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_keystone_container-0d7a4d0c] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_cert_container-6f5a612d] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_repo_container-cb57e740] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_neutron_server_container-2336cf92] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_glance_container-df8f6782] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_cinder_scheduler_container-45595f8a] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_repo_container-64a71607] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_neutron_agents_container-80cc6d88] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_api_os_compute_container-ca331872] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_api_metadata_container-e444e98d] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_memcached_container-7df01f14] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_conductor_container-3891b9ad] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_galera_container-2c14a508] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_cinder_api_container-97bb86b8] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_rsyslog_container-95b449dc] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_rabbit_mq_container-19de8a9a] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_rabbit_mq_container-db8160a0] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_heat_apis_container-429e480d] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_galera_container-dea4ed6c] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_heat_engine_container-09eb5ad5] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_galera_container-285a0792] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_rabbit_mq_container-ffa9d583] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_console_container-0a481d09] => error while evaluating conditional: inventory_hostname in groups['ceph_all']

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/setup-maas.retry

compute01                  : ok=153  changed=41   unreachable=1    failed=0
infra01                    : ok=144  changed=29   unreachable=1    failed=0
infra01_cinder_api_container-97bb86b8 : ok=119  changed=4    unreachable=1    failed=0
infra01_cinder_scheduler_container-45595f8a : ok=119  changed=4    unreachable=1    failed=0
infra01_galera_container-285a0792 : ok=120  changed=4    unreachable=1    failed=0
infra01_galera_container-2c14a508 : ok=120  changed=5    unreachable=1    failed=0
infra01_galera_container-dea4ed6c : ok=120  changed=5    unreachable=1    failed=0
infra01_glance_container-df8f6782 : ok=122  changed=8    unreachable=1    failed=0
infra01_heat_apis_container-429e480d : ok=125  changed=12   unreachable=1    failed=0
infra01_heat_engine_container-09eb5ad5 : ok=116  changed=0    unreachable=1    failed=0
infra01_horizon_container-422f2991 : ok=119  changed=4    unreachable=1    failed=0
infra01_horizon_container-f3df59bf : ok=119  changed=4    unreachable=1    failed=0
infra01_keystone_container-0d7a4d0c : ok=119  changed=4    unreachable=1    failed=0
infra01_keystone_container-2d73e396 : ok=119  changed=4    unreachable=1    failed=0
infra01_memcached_container-7df01f14 : ok=119  changed=4    unreachable=1    failed=0
infra01_neutron_agents_container-80cc6d88 : ok=134  changed=24   unreachable=1    failed=0
infra01_neutron_server_container-2336cf92 : ok=119  changed=4    unreachable=1    failed=0
infra01_nova_api_metadata_container-e444e98d : ok=119  changed=4    unreachable=1    failed=0
infra01_nova_api_os_compute_container-ca331872 : ok=119  changed=4    unreachable=1    failed=0
infra01_nova_cert_container-6f5a612d : ok=119  changed=4    unreachable=1    failed=0
infra01_nova_conductor_container-3891b9ad : ok=119  changed=4    unreachable=1    failed=0
infra01_nova_console_container-0a481d09 : ok=122  changed=8    unreachable=1    failed=0
infra01_nova_scheduler_container-638e2856 : ok=119  changed=4    unreachable=1    failed=0
infra01_rabbit_mq_container-19de8a9a : ok=119  changed=4    unreachable=1    failed=0
infra01_rabbit_mq_container-db8160a0 : ok=119  changed=4    unreachable=1    failed=0
infra01_rabbit_mq_container-ffa9d583 : ok=120  changed=4    unreachable=1    failed=0
infra01_repo_container-64a71607 : ok=116  changed=0    unreachable=1    failed=0
infra01_repo_container-cb57e740 : ok=116  changed=0    unreachable=1    failed=0
infra01_rsyslog_container-95b449dc : ok=116  changed=0    unreachable=1    failed=0
infra01_utility_container-0276d803 : ok=118  changed=0    unreachable=1    failed=0

**Comment by byronmccollum** [comment]
I'm seeing the same thing.

**Comment by andymcc** [comment]
This is fixed in the new MaaS work - so you shouldn't see this if you have no ceph nodes.

**Comment by d34dh0r53** [comment]
Let's hold on this until we see of the new MaaS refactor fixes the issue.

**Comment by stevelle** [comment]
kilo fix should be included in #531

**Comment by LeoG36** [comment]
Still seeing the following error in r11.0.2 when running through maas.

ERROR: found role at /opt/rpc-openstack/rpcd/playbooks/roles/ceph-common, but cannot find /opt/rpc-openstack/rpcd/playbooks/roles/ceph-common/tasks/main or /opt/rpc-openstack/rpcd/playbooks/roles/ceph-common/handlers/main or /opt/rpc-openstack/rpcd/playbooks/roles/ceph-common/vars/main or /opt/rpc-openstack/rpcd/playbooks/roles/ceph-common/defaults/main or /opt/rpc-openstack/rpcd/playbooks/roles/ceph-common/meta/main or /opt/rpc-openstack/rpcd/playbooks/roles/ceph-common/library

**Comment by LeoG36** [comment]
Also seeing this error at the end of the setup.

TASK: [rpc_maas | Discover Ceph facts] ****************************************
fatal: [738931-infra01_utility_container-6ae88942] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738931-infra01_heat_engine_container-0cbfd22d] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738931-infra01_repo_container-18935e5d] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738978-infra03_repo_container-43ce604d] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738990-logging01_elasticsearch_container-091daf98] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738978-infra03_utility_container-8adf07d8] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738990-logging01_logstash_container-52baad9c] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738990-logging01_kibana_container-9603f4c8] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738978-infra03_heat_engine_container-dada9ebe] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738977-infra02_utility_container-95d48968] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738977-infra02_repo_container-d5b5413d] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738977-infra02_heat_engine_container-0951b2e0] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'
fatal: [738990-logging01_rsyslog_container-c629820f] => Failed to template {% if inventory_hostname in groups['ceph_all'] groups['ceph_all'] is defined and inventory_hostname in groups['ceph_all'] %} True {% else %} False {% endif %}: template error while templating string: expected token 'end of statement block', got 'groups'

**Comment by BjoernT** [comment]
Don't think this is an issue anymore after we added the condition if the ceph_all group is even defined ?

**Comment by andymcc** [comment]
I believe this is fixed? 
One of the other things that should be done is to add the env.d/ vars for ceph, even though you aren't using ceph. This will then define the ceph_all group and the if check will complete successfully.

**Comment by andymcc** [comment]
I'm going to close this - since it should be resolved now, but if you are still running into this issue please update me/drop me an email and I'd be happy to resolve it (again)!

**Comment by BjoernT** [comment]
:+1:  The upstream review is at https://github.com/ceph/ceph-ansible/pull/452
